# Generated by Django 4.0.3 on 2022-03-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_teacher_student_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.CharField(default='English', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
