# Generated by Django 4.0.3 on 2022-03-13 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_teacher_subjects_alter_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='age',
        ),
    ]
