# Generated by Django 4.0.3 on 2022-03-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_teacher_language_teacher_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
